version: "3"

services:
  clash-server:
    image: dreamacro/clash:v1.11.8
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "9090:9090"
    restart: always
    network_mode: "host"

  clash-dashboard:
    image: centralx/clash-dashboard
    ports:
      - "8081:80"
    restart: always

