version: "3"

services:
  clash-server:
    image: dreamacro/clash:v1.11.8
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${EXTERNAL_PORT}:${EXTERNAL_PORT}"
    restart: always
    network_mode: "host"

  clash-dashboard:
    image: centralx/clash-dashboard
    ports:
      - "8081:80"
    restart: always

